### ISSUE TITLE
Add Hexo 6.x to peer dependencies.

### ISSUE THREAD

**Issue by goodhoko** [hexojs/hexo-filter-responsive-images#195]
Hexo 6.1 was relaesed almost a [year ago](https://github.com/hexojs/hexo/releases/tag/6.1.0). I can't update to it because this plugin defines it as peer dependency with `"hexo": "3.x || 4.x || 5.x"` and npm (since v7) treats such mismatch as an error.

I briefly tested this plugin with hexo 6.3 and it worked just fine.

Can we change the hexo peer-dependency version to include 6.x? What are the necessary steps? I'd be glad to submit a PR. .)

Take care!

**Comment by ertrzyiks** [comment]
Indeed, time for the update. I will take care of that.

**Comment by ertrzyiks** [comment]
Released as 1.8.0, thanks for reporting it @goodhoko

**Comment by goodhoko** [comment]
Thanks for such a fast action! Let's hope for no regressions. .)

Btw, for anyone who, for some reason can't update this plugin: you can overcome the errors of mismatched peer dependencies with the [`--legacy-peer-deps`](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps) flag.
