### ISSUE TITLE
Filter not processing in Series

### ISSUE THREAD

**Issue by petrstepanov** [hexojs/hexo-filter-responsive-images#207]
Hi, cool plugin! Correct me if I'm wrong but I believe I found a buggy behavior here. Plugin does not process images in series as intended. The problem is in file "responsive_images.js", line 39:

https://github.com/hexojs/hexo-filter-responsive-images/blob/a16790f445039acfde9a26869b765b4be7db7ea1/lib/responsive_images.js#L39

```
return route.set(...)
```
which is not a Bluebird promise. This leads to simultaneous processing of all the images - very resourceful. Instead one should return the Bluebird promise and resolve it after the sharp transformation is completed. Please find a code snippet below:

```
return new Promise(function (resolve, reject) {
  var img = sharp(buffer).rotate();
  var resizeOptions = getResizeOptions(hexo, config)
  applySharpApiOptions(img, config).resize(config.width, config.height, resizeOptions).toBuffer().then(function (buffer) {
    route.set(newPath, buffer);
    resolve();
  });
});
```

**Comment by ertrzyiks** [comment]
Hey @petrstepanov , thanks for providing the technical analysis of the problem. Could you briefly describe why it's a problem for you? You mentioned the process to be `very resourceful`, so you find the current behavior too CPU intensive to the point that it breaks in your environment?

**Comment by petrstepanov** [comment]
For large AVIF images in particular yes it was breaking g the environment since all conversions started simultaneously. You can double check it with outputting a timestamp to console before each image starts resizing.

**Comment by ertrzyiks** [comment]
My very first attempt to address the problem is https://github.com/hexojs/hexo-filter-responsive-images/pull/208

Tests are green but I need to verify if it's effective though

**Comment by ertrzyiks** [comment]
@petrstepanov I realized that it may be OK to have all the resized images registered in the routing because **this plugin** doesn't render all of them at once. It's responsibility of the core hexo and after a quick check I would suggest you to try to limit concurrency using `--concurrency` param of `hexo generate` command.

https://hexo.io/docs/commands#generate

**Comment by petrstepanov** [comment]
> limit concurrency using `--concurrency` param of `hexo generate` command.

Dear Mateusz, thank you very much for pointing this out. It may be helpful to note this in the README. I am closing the issue now.

**Comment by ertrzyiks** [comment]
> It may be helpful to note this in the README.
Agree, I will close my current PR and submit a new one with this information.
