### ISSUE TITLE
How to use scaled images in rendered post content?

### ISSUE THREAD

**Issue by goodhoko** [hexojs/hexo-filter-responsive-images#94]
Hello, thanks a lot for this plugin. I successfully incorporated it into my theme templates with the `image_version(path {prefix: size})` helper.

Unfortunately, I can't find any information on how can I use the scaled images in the rendered post content. It would be nice to describe how one can do that in the README.

Best!

Jen

PS: If you can point me to an information on how that can be done, I can prepare a PR to extend the README with that into.

**Comment by ertrzyiks** [comment]
You can do that with a custom tag https://hexo.io/api/tag We could register the tag in this plugin, don't know why it's missing. Probably just because nobody asked for it so far.

Let's agree on some API and add the tag to this plugin. Could you achieve what we need with that simple tag?

```
{% image_version /path/to/the/file.jpg small Description %}
```

```
<img src="/path/to/the/smal-file.jpg" alt="Description" />
```
?

**Comment by goodhoko** [comment]
I assume that
1) This should not require change of the post source itself. Ie. the writers shouldn't have to use anything different than the default `{% asset_img %}` tag. I believe images in the post content is so broadly used feature it should not be dependent on any plugin.
2) The rendered html should be controlled by the theme not the plugin. Every theme may want to render the html for an image differently.
3) It is ok if a theme is dependent on a plugin.

_Do you agree?_

From that I deduce the best approach would be if a theme could intercept rendering of the default `{% asset_img %}` tag and customize the output. Possibly using a helper provided by this plugin. The `image_version(path {prefix: size})` helper should do the job.

I'm not sure if Hexo provides any way to achieve this?

**Comment by ertrzyiks** [comment]
I agree on point 3. Not sure if 2. is already possible or a feature request to Hexo itself. 1. would be nice to have indeed, I need to dig into the code a bit to know what is possible. Maybe we can override `asset_img` tag.

**Comment by goodhoko** [comment]
> Not sure if 2. is already possible or a feature request to Hexo itself.

Yeah, me neither. I couldn't find any information on this in the official hexo docs. In my theme I ended up hooking into the `after_post_render` stage and altering the output with a body regex

```js
// ugly, but works
hexo.extend.filter.register('after_post_render', function(data) {
    ...
    data.content = data.content.replace(/<img [^>]+>/g, function (img) {...})
}
```

**Comment by ertrzyiks** [comment]
I will have some time for digging into it over the weekend. 🤞

**Comment by ertrzyiks** [comment]
I found that most of the related plugins are based on `after_post_render` and regular expressions indeed. Otherwise, we have Markdown's `![]()` and Hexo's asset_img tag to support and things are getting complicated.

We could possibly (haven't tried yet) overwrite the `asset_img` helper and provide plugin for markdown-it to have less hacky approach but to cover all the cases we stuck with the `after_post_render` hook.

It would be something like:
```
hexo.extend.filter.register('after_post_render', function(data) {
    ...
    data.content = data.content.replace(/<img [^>]+>/g, function (img) {
      return <img src=${hexo.helpers. image_version(src)}>``
    })
}
```

@goodhoko do you need some logic around the version or all images from posts would be scaled to same size?

**Comment by ertrzyiks** [comment]
A simple version assuming all post need `thumb` prefix for images.

```js
function processImages(source) {
  var imageVersion = hexo.extend.helper.get('image_version')

  return source.replace(/<img([^>]+)?>/igm, (s, attr) => {
    attr = attr.replace(/src="([^"]+)?"/, (s, img) => {
      return `src="${imageVersion(img, { prefix: 'thumb' })}"`
    })
    return `<img${attr} />`
  })
}

hexo.extend.filter.register('after_post_render', function(data) {
  data.content = processImages(data.content)
  return data
})
```

**Comment by goodhoko** [comment]
> I found that most of the related plugins are based on after_post_render and regular expressions indeed. Otherwise, we have Markdown's ![]() and Hexo's asset_img tag to support and things are getting complicated.

Considering these two fact I guess, that at this point it's fair to advertise this as the canonical way for images in MD content. If you ok with that, I will create a PR to add this to the readme of this plugin.

**Comment by ertrzyiks** [comment]
Yup, let's have it documented. I will happily accept a PR with the simplify code that worked for you 👍 thanks @goodhoko
